### ISSUE TITLE
the .d.ts is not generated

### ISSUE THREAD

**Issue by Dargos69** [jaystack/jaysvcutil#1]
it was generated with jaysvcutil.exe
is there no option ?

**Comment by richardliebmann** [comment]
+1 for .d.ts support

**Comment by jpattersonz** [comment]
+1

**Comment by sheam** [comment]
Is this feature coming? We use it all the time with the old JaySvcUtil in JayData Pro.

**Comment by PeterAronZentai** [comment]
Yes... very high on the list. Only another ctp release to be done before - this week.

**Comment by lazarv** [comment]
Feature now available, just update from npm.
See [readme](https://github.com/jaystack/jaysvcutil#readme) for more information.
