### ISSUE TITLE
Exception when -n specified

### ISSUE THREAD

**Issue by a2dude** [jaystack/jaysvcutil#2]
C:\WIP\Projects\OData\jaydata\npm\jaysvcutil>jaysvcutil --metadataUri http://services.odata.org/V4/Northwind/Northwind.svc --out northwind.js -n bosh

Type generated: NorthwindModel.Category
Type generated: NorthwindModel.CustomerDemographic
Type generated: NorthwindModel.Customer
Type generated: NorthwindModel.Employee
Type generated: NorthwindModel.Order_Detail
Type generated: NorthwindModel.Order
Type generated: NorthwindModel.Product
Type generated: NorthwindModel.Region
Type generated: NorthwindModel.Shipper
Type generated: NorthwindModel.Supplier
Type generated: NorthwindModel.Territory
Type generated: NorthwindModel.Alphabetical_list_of_product
Type generated: NorthwindModel.Category_Sales_for_1997
Type generated: NorthwindModel.Current_Product_List
Type generated: NorthwindModel.Customer_and_Suppliers_by_City
Type generated: NorthwindModel.Invoice
Type generated: NorthwindModel.Order_Details_Extended
Type generated: NorthwindModel.Order_Subtotal
Type generated: NorthwindModel.Orders_Qry
Type generated: NorthwindModel.Product_Sales_for_1997
Type generated: NorthwindModel.Products_Above_Average_Price
Type generated: NorthwindModel.Products_by_Category
Type generated: NorthwindModel.Sales_by_Category
Type generated: NorthwindModel.Sales_Totals_by_Amount
Type generated: NorthwindModel.Summary_of_Sales_by_Quarter
Type generated: NorthwindModel.Summary_of_Sales_by_Year
C:\Users\andy\AppData\Roaming\npm\node_modules\jaysvcutil\node_modules\jaydata-odatajs\lib\odata\odatautils.js:385
            throw err;
            ^

TypeError: Cannot read property 'splice' of undefined
    at C:\Users\andy\AppData\Roaming\npm\node_modules\jaysvcutil\node_modules\jaydata-dynamic-metadata\lib\metadata.js:451:17
    at Array.map (native)
    at Metadata.processMetadata (C:\Users\andy\AppData\Roaming\npm\node_modules\jaysvcutil\node_modules\jaydata-dynamic-metadata\lib\metadata.js:397:49)
    at requestData (C:\Users\andy\AppData\Roaming\npm\node_modules\jaysvcutil\node_modules\jaydata-dynamic-metadata\lib\metadataHandler.js:45:42)
    at C:\Users\andy\AppData\Roaming\npm\node_modules\jaysvcutil\node_modules\jaydata-odatajs\lib\odata\odatautils.js:382:13
    at IncomingMessage.<anonymous> (C:\Users\andy\AppData\Roaming\npm\node_modules\jaysvcutil\node_modules\jaydata-odatajs\lib\odata\net.js:174:21)
    at emitNone (events.js:85:20)
    at IncomingMessage.emit (events.js:179:7)
    at endReadableNT (_stream_readable.js:906:12)
    at nextTickCallbackWith2Args (node.js:474:9)

**Comment by lazarv** [comment]
Fixed in [jaydata-dynamic-metadata](https://github.com/jaystack/jaydata-dynamic-metadata/commit/dedbc19384546307105cb8194d4cafa186a819ba)
Dependency update in jaysvcutil.

Commit 2f08514 closes #2
